name: ecommerce_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: "^3.7.0"  # Added the Dart SDK constraint

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.9
  sqflite: ^2.3.0
  font_awesome_flutter: ^10.6.0
  google_fonts: ^6.2.1
  path_provider: ^2.1.2
  provider: ^6.1.0
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  sqflite_common_ffi: ^2.3.4+4

  # Firebase dependencies
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.4.5
  firebase_messaging: ^15.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
